<?php

include("../../../config/db.php");
if (isset($_SESSION['managerID'])) {
require("fpdf.php");


$today = date('Y-m-d');
if (date('D') != 'Mon') {
    //take the last monday
    $staticstart = date('Y-m-d', strtotime('last Monday'));
} else {
    $staticstart = date('Y-m-d');
}

//always next saturday
if (date('D') == 'Sun') {
    $staticfinish = date('Y-m-d');
} else {
    $staticfinish = date('Y-m-d', strtotime('next Sunday'));
}
//previous week start date and end date
$staticlastfinist = date('Y-m-d', strtotime($staticstart . "-1 days"));
$staticlaststart = date('Y-m-d', strtotime($staticlastfinist . "-6 days"));

class PDF extends FPDF
{
    // Page header
    function Header()
    {
        // Logo
        $this->Image('../../../assets/Images/logo.png', 10, 10, 20);
        // Arial bold 15
        $this->SetFont('Arial', 'B', 14);
        // Move to the right
        //$this->Cell(80);
        // Title
        $this->Cell(200, 10, 'FLEX SPORTS', 0, -10, 'C');
        $this->Ln();
        $this->SetFont('Times', '', 10);
        $this->Cell(200, 5, '742/7A, Barnes Place, Colombo 7,10115', 0, 0, 'C');
        $this->Ln();
        $this->Cell(200, 5, 'Phone: +94 11 278 9467       Email:flexsports@gmail.com', 0, 0, 'C');
        // Line break
        $this->Ln(20);
    }

    // Page footer
    function Footer()
    {
        include("../../../config/db.php");
        // Position at 1.5 cm from bottom
        $this->SetY(-15);
        // Arial italic 8
        $this->SetFont('Arial', 'I', 8);
        // Page number
        $today = date('Y-m-d');
        $time=time();

        $get_manager_query=mysqli_query($conn, "SELECT FName,LName FROM manager_staff WHERE Email='$_SESSION[managerID]';");
        $get_manager_result=mysqli_fetch_assoc($get_manager_query);

        $Fname=$get_manager_result['FName'];
        $Lname=$get_manager_result['LName'];

        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'R');
        $this->Ln();
        $this->Cell(0, -10, 'Generated by ' . $Fname .' '.$Lname. ' on ' . $today.' at '.$time, 0, 0, 'L');
    }
    function FancyTable($staticfinish, $staticstart, $staticlaststart, $staticlastfinist, $conn)
    {
        $header = array('Facility', 'Confirmed', 'Pending', 'Cancelled', 'Total', 'Last Week');
        $this->SetFillColor(39, 69, 108);
        $this->SetTextColor(255);
        $this->SetDrawColor(39, 69, 108);
        $this->SetLineWidth(.1);
        $this->SetFont('', 'B');
        $w = array(40, 30, 30, 30, 30, 30);
        for ($i = 0; $i < count($header); $i++) {
            $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
        }
        $this->Ln();
        // headder compleated


        $this->SetFillColor(255);
        $this->SetDrawColor(39, 69, 108);
        $this->SetTextColor(39, 69, 108);
        $this->SetFont('');


        $get_facilities_query = mysqli_query($conn, "SELECT FacilityName FROM facility WHERE FacilityName!='Office' AND FacilityName!='Reception'GROUP BY FacilityName;");
        if (mysqli_num_rows($get_facilities_query) > 0) {
            $j = 0;
            while ($get_facilities_result = mysqli_fetch_array($get_facilities_query)) {
                $FaciName = $get_facilities_result["FacilityName"];

                $data_reservation_query = mysqli_query($conn, "SELECT COUNT(ReservationNo) AS FaciRes FROM reservation WHERE date>='$staticstart' AND date<='$staticfinish' AND FacilityName='$FaciName';");
                $data_reservation_result = mysqli_fetch_assoc($data_reservation_query);
                $this_week = $data_reservation_result['FaciRes'];

                $lastweek_reservation_query = mysqli_query($conn, "SELECT COUNT(ReservationNo) AS FaciRes FROM reservation WHERE date>='$staticlaststart' AND date<='$staticlastfinist' AND FacilityName='$FaciName';");
                $lastweek_reservation_result = mysqli_fetch_assoc($lastweek_reservation_query);
                $last_week = $lastweek_reservation_result['FaciRes'];

                $confirmed_recervation_query = mysqli_query($conn, "SELECT  COUNT(ReservationNo) AS ConfirmRes FROM reservation WHERE date>='$staticstart' AND date<='$staticfinish' AND ReservationStatus='Confirmed'AND FacilityName='$FaciName';");
                $confirmed_recervation_result = mysqli_fetch_assoc($confirmed_recervation_query);
                $confirmed = $confirmed_recervation_result['ConfirmRes'];

                $pending_recervation_query = mysqli_query($conn, "SELECT  COUNT(ReservationNo) AS PendingRes FROM reservation WHERE date>='$staticstart' AND date<='$staticfinish' AND ReservationStatus='Pending'AND FacilityName='$FaciName';");
                $pending_recervation_result = mysqli_fetch_assoc($pending_recervation_query);
                $pending = $pending_recervation_result['PendingRes'];

                $cancel_recervation_query = mysqli_query($conn, "SELECT  COUNT(ReservationNo) AS CancelRes FROM reservation WHERE date>='$staticstart' AND date<='$staticfinish' AND ReservationStatus='Cancelled'AND FacilityName='$FaciName';");
                $cancel_recervation_result = mysqli_fetch_assoc($cancel_recervation_query);
                $cancel = $cancel_recervation_result['CancelRes'];


                $data = array($FaciName, $confirmed, $pending, $cancel, $this_week, $last_week);
                for ($k = 0; $k < count($data); $k++) {
                    $this->Cell($w[$k], 7, $data[$k], 1, 0, 'C', true);
                }
                $this->Ln();
            }
            $j++;
        }
        $this->SetFillColor(224, 235, 255);
        $this->SetTextColor(0);
        $this->SetFont('');
    }

    function inquiry($staticfinish, $staticstart, $conn)
    {
        $get_inquiry_query = mysqli_query($conn, "SELECT InquiryType, COUNT(InquiryNo) AS TotalInq FROM inquiry WHERE date>='$staticstart' AND date<='$staticfinish' GROUP BY InquiryType ;");
        if (mysqli_num_rows($get_inquiry_query) > 0) {
            $header = array('Inquiry Type', 'Count');

            $this->SetFillColor(39, 69, 108);
            $this->SetTextColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetLineWidth(.3);
            $this->SetFont('', 'B');
            $w = array(40, 30, 30);
            for ($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
    
            $this->SetFillColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetTextColor(39, 69, 108);
            $this->SetFont('');
            if (mysqli_num_rows($get_inquiry_query) > 0) {
                $j = 0;
                while ($get_inquiry_result = mysqli_fetch_array($get_inquiry_query)) {
                    $InqType = $get_inquiry_result['InquiryType'];
                    $Inqcount = $get_inquiry_result['TotalInq'];
                    $data = array($InqType, $Inqcount);
                    for ($k = 0; $k < count($data); $k++) {
                        $this->Cell($w[$k], 7, $data[$k], 1, 0, 'C', true);
                    }
                    $this->Ln();
                }
                $j++;
            }
        } else {
            $this->SetFillColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetTextColor(39, 69, 108);
            $this->SetFont('');
            $this->Cell(200, 0, 'No Inquires for this week',0, 0, 'L');
        }
        $this->SetFillColor(224, 235, 255);
        $this->SetTextColor(0);
        $this->SetFont('');
    }
    function users($conn){
        $get_users_query = mysqli_query($conn, "SELECT UserType , COUNT(ID) AS Totalusr FROM user_login GROUP BY UserType ;");
        if (mysqli_num_rows($get_users_query ) > 0) {
            $header = array('User Type', 'Count');

            $this->SetFillColor(39, 69, 108);
            $this->SetTextColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetLineWidth(.3);
            $this->SetFont('', 'B');
            $w = array(40, 30, 30);
            for ($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
    
            $this->SetFillColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetTextColor(39, 69, 108);
            $this->SetFont('');
            if (mysqli_num_rows($get_users_query) > 0) {
                $j = 0;
                while ($get_user_result = mysqli_fetch_array($get_users_query)) {
                    if ($get_user_result['UserType']=='customer'){
                        $UsrType ='Customer';
                    }elseif ($get_user_result['UserType']=='receptionist') {
                        $UsrType ='Receptionist';
                    }elseif ($get_user_result['UserType']=='manager') {
                        $UsrType ='Manager';
                    }elseif ($get_user_result['UserType']=='facilityworker') {
                        $UsrType ='Facility Worker';
                    }
                   
                    $Usrcount = $get_user_result['Totalusr'];
                    $data = array($UsrType,  $Usrcount);
                    for ($k = 0; $k < count($data); $k++) {
                        $this->Cell($w[$k], 7, $data[$k], 1, 0, 'C', true);
                    }
                    $this->Ln();
                }
                $j++;
            }
        } else {
            $this->SetFillColor(255);
            $this->SetDrawColor(39, 69, 108);
            $this->SetTextColor(39, 69, 108);
            $this->SetFont('');
            $this->Cell(200, 0, 'No Users in the system',0, 0, 'L');
        }
        $this->SetFillColor(224, 235, 255);
        $this->SetTextColor(0);
        $this->SetFont('');

    }
}

// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 12);

$pdf->Cell(200, -10, 'Report for the week from ' . $staticstart . ' to ' . $staticfinish, 0, 0, 'C');
$pdf->Ln(0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(200, 25, 'Reservations', 0, 0, 'L');
$pdf->Ln();

// reservation sub topic related stuff

$pdf->FancyTable($staticfinish, $staticstart, $staticlaststart, $staticlastfinist, $conn);
$pdf->Ln(0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(200, 25, 'Inquiries', 0, 0, 'L');
$pdf->Ln();
$pdf->inquiry($staticfinish, $staticstart, $conn);
$pdf->Ln(0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(200, 25, 'Users', 0, 0, 'L');
$pdf->Ln();
$pdf->users($conn);
$pdf->Output($name='I','report.pdf',true);


// Data for reservation bar chart

mysqli_close($conn);
} else {
    header('Location: ../login.php');
}
